version: "3.7"

services:
  frontend:
    image: registry.bjarke.xyz/personal-website
    build:
      context: ./src
    networks:
      - swarm-overlay

networks:
  swarm-overlay:
    external: true
    name: swarm-overlay
